In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("country_salary.csv")
df

In [ ]:
df.shape #columns and rows

In [ ]:
df.head

In [ ]:
df.tail

In [ ]:
df.columns

In [ ]:
df.describe()

In [ ]:
df.nunique()

In [ ]:
df['age'].nunique

In [ ]:
df.isnull().sum()

In [42]:
df.size

32

In [ ]:
#to remove specific column
#delete_data=df.drop('purchase')

In [43]:
# x+y=z  x and y =independent variables / z=dependent variable
#extracting independent variables
x=df[['country','age','salary']].values

In [44]:
#extract dependent variables
y=df[['purchase']].values
y


array([['no'],
       ['yes'],
       ['yes'],
       ['no '],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes']], dtype=object)

# finding missing values in given data set

In [45]:
from sklearn.impute import SimpleImputer

In [46]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [47]:
imputer=imputer.fit(x[:,1:3])

In [48]:
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['france', 44.0, 72000.0],
       ['spain', 23.0, 65000.0],
       ['germany', 26.0, 42000.0],
       ['spain', 25.0, 56000.0],
       ['germany', 33.285714285714285, 76000.0],
       ['france', 46.0, 48000.0],
       ['germany', 42.0, 60142.857142857145],
       ['france', 27.0, 62000.0]], dtype=object)

# Non numeric label converts into numeric label

In [49]:
from sklearn.preprocessing import LabelEncoder

In [50]:
LabelEncoder_x=LabelEncoder()
x[:,0]=LabelEncoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 23.0, 65000.0],
       [1, 26.0, 42000.0],
       [2, 25.0, 56000.0],
       [1, 33.285714285714285, 76000.0],
       [0, 46.0, 48000.0],
       [1, 42.0, 60142.857142857145],
       [0, 27.0, 62000.0]], dtype=object)

In [51]:
from sklearn.preprocessing import OneHotEncoder 

In [ ]:
onehotencosder=OneHotEncoder()
onehotencosder.fit_transform(df.country.values.reshape(-1,1)).toarray() 

In [52]:
LabelEncoder_y=LabelEncoder()
y=LabelEncoder_y.fit_transform(y)
y

c:\Users\banka\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 2, 2, 1, 2, 0, 2, 2])

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [55]:
x_train

array([[2, 23.0, 65000.0],
       [0, 27.0, 62000.0],
       [2, 25.0, 56000.0],
       [0, 44.0, 72000.0],
       [0, 46.0, 48000.0],
       [1, 33.285714285714285, 76000.0]], dtype=object)

In [56]:
x_test

array([[1, 42.0, 60142.857142857145],
       [1, 26.0, 42000.0]], dtype=object)

In [57]:
y_test

array([2, 2])

In [58]:
y_train

array([2, 2, 1, 0, 0, 2])

In [59]:
from sklearn.preprocessing import StandardScaler

In [60]:
sc_x=StandardScaler()

In [61]:
x_train=sc_x.fit_transform(x_train)

In [62]:
x_test=sc_x.fit_transform(x_test)

In [63]:
x_train

array([[ 1.29986737, -1.11175886,  0.19527995],
       [-0.92847669, -0.66916292, -0.12426906],
       [ 1.29986737, -0.89046089, -0.76336707],
       [-0.92847669,  1.21186985,  0.94089429],
       [-0.92847669,  1.43316783, -1.61549775],
       [ 0.18569534,  0.026345  ,  1.36695963]])

In [64]:
x_test

array([[ 0.,  1.,  1.],
       [ 0., -1., -1.]])